return {
	"Richard Timlin",
	"RatherBe",
	"Crunchy Churro",
	"energy329 ",
	"miggyb ",
	"Daniel ",
	"RyutoSetsujin",
	"Ayanehatte",
	"Juan Pablo Rosales Cruz",
	"Chris",
	"Jacob Trewe",
	"Dark Wolf",
	"Heinrich VandenBoogie",
	"Pirkins",
	"notnola",
	"Casuallynoted",
	"Richard Wilder",
	"SockHungryClutz",
	"Bryan Dover",
	"Christian May",
	"Yiftach Katz",
	"The T",
	"Joseph Madamba",
	"Dalkor",
	"Andrés Choque Lopez",
	"wiojhfwoeijf ",
	"Matthew Youmans",
	"Stephen Joiner",
	"#1 Fan",
	"Fumoffu Cerberus",
	"orlypro lea",
	"shockdude",
	"nullobsi",
	"eudes",
	"諸井智貴",
	"Topias",
	"Oleg Sergeev",
	"Kenneth J Lias",
	"Robert",
	"dirtydigital",
	"Christopher Daub",
	"Nicolas ",
	"Thai Pangsakulyanont",
	"KebinuChiousu",
	"Carl Shan",
	"Johannes Unger",
	"roger clark",
	"Nitrobear ",
	"Keirsten Machine",
	"Chris",
	"Amanda Steadman",
	"KingCommandoJimmoTheIII",
	"CowEye",
	"Patrick Lonergan",
	"Scott Walters",
	"Fae Laren",
	"Brad Beachum",
	"LaForge ",
	"KingJ ",
	"S. Tan",
	"Icaro1447 ",
	"EoInsanity ",
	"Sam Sutherland",
	"AnimusYosho ",
	"Joseph Broderick",
	"Rolando Cammarano",
	"Dimitri Lee",
	"Patrick Daxboeck",
	"NJ ",
	"HSM",
	"Jubo (Justin B.)",
	"Link Wang",
	"Nhan ML",
	"Hubie ",
	"Prcuvu ",
	"David Bernat",
	"invalidname",
	"Devin Duplantis",
	"Not John",
	"Christopher Davis",
	"J ",
	"Chriszo ",
	"weaw lad",
	"Matthew Barton",
	"Valheru ",
	"Namwen ",
	"Will ",
	"DakronV ",
	"Mark Watson",
	"Stormalize ",
	"nythil",
	"Cooly568 ",
	"Kelly Maguire",
	"Nenza Strittki",
	"Douglas Shell",
	"Marko Boltizar",
	"Kevin Turner",
	"Alexander Haibl",
	"Gabriele Massa",
	"Carl ",
	"Chubby Lumpkins",
	"David Rice",
	"Emmanuel Bergeron",
	"Joel-Robert-Justiawan",
	"Knight Gaetes",
}